title: Cheondi
description: Unity Developer`s Blog
author: Cheondi
avatar: /icon.png
email: kwon95799@gmail.com
tag : 엉망진창 가로세로.

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

url  :  "https://cheondi.github.io/"

paginate: 10
markdown: kramdown
excerpt_length: 0
# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
 
disqus-identifier: disqus_HnaiSxNCIy

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
#logo: logo.png
#social:
#  name: Shangzhi Huang
#  links:
#    - https://twitter.com/ngzhio
 #   - https://www.facebook.com/ngzhio
 #   - https://github.com/ngzhio
google_site_verification: googlef48f67f4b34213ac
lang: en
